### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by naruto0728** [opsre/go-ldap-admin#358]
#### 您使用的版本？ | Your usage version?
- docker.mirrors.sjtug.sjtu.edu.cn/osixia/openldap:1.4.0
#### 您使用的场景？ | Your usage scenarios?
- 登录场景
#### 您做了什么操作？ | What did you do?
- 什么也没做。
#### 您遇到了什么问题？ | What are your problems?
- 现在登录不上去了

![image](https://github.com/eryajf/go-ldap-admin/assets/28386262/42b268c1-027b-4c54-a44b-a8ca70653e37)
![image](https://github.com/eryajf/go-ldap-admin/assets/28386262/8d4a4442-bc4c-403e-87e6-dffce719fb10)

#### 您期望的结果是怎样的？ | What is your expected outcome?
- 期望可以正常的进行登录

**Comment by eryajf** [comment]
您好 @naruto0728👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @naruto0728. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by naruto0728** [comment]
想要请问一下像这种我该怎么解决呀？

**Comment by eryajf** [comment]
你这是新部署，还是什么场景，上下文信息给多一些

**Comment by naruto0728** [comment]
我这个是已经部署了一段时间了，也使用了一段时间了，今天上去突然提示上不去。401私钥认证不通过

**Comment by eryajf** [comment]
就是正常使用，没有任何变动，就登录不上去了吗？

**Comment by naruto0728** [comment]
是的。是因为server.csr和server.key过期了吗？

**Comment by naruto0728** [comment]
是通过docker-compose启动的。我试着尝试重启，但是重启了还是这样

**Comment by eryajf** [comment]
看下前后端的镜像，是不是拉了新的镜像？

**Comment by naruto0728** [comment]
应该没有的，因为docker-compose里边写的是固定的版本呀

**Comment by eryajf** [comment]
前后端呢，因为前后端貌似用的是latest的版本

**Comment by naruto0728** [comment]
也是固定的版本
![image](https://github.com/eryajf/go-ldap-admin/assets/28386262/e9fb19c7-8682-41a6-83be-3690405e6c9b)

**Comment by eryajf** [comment]
是单个应用无法登陆，还是所有用户都无法登陆了。

**Comment by naruto0728** [comment]
所有的用户都登录不了呢,都提示同样的错误

**Comment by eryajf** [comment]
当初你部署的时候，秘钥用的是默认的，还是自己生成的呢

**Comment by naruto0728** [comment]
这个我不太清楚。因为之前不是我搞的。所以说现在能重新生成秘钥解决么？

**Comment by eryajf** [comment]
> 这个我不太清楚。因为之前不是我搞的。所以说现在能重新生成秘钥解决么？

现在ldap认证相关的服务应该都还能正常使用吧。

重新生成秘钥是不行的，因为密码等原来的数据都已经基于老的秘钥落库了。

还是排查看看是不是有什么变更，应该不会在没有变更的情况下，无缘无故无法登陆的。

**Comment by eryajf** [comment]
你先比对一下里边用的密钥信息，和当前项目里最新版本的密钥是不是一样的，如果是一样的，可以考虑基于最新版本新建。然后再把老数据导入的思路来处理。

务必注意，请在一个新的服务器环境里验证，不要在原来的环境验证。
