### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by shistory** [opsre/go-ldap-admin#373]
2024/11/23 02:04:53 ERRO [获取用户列表失败 Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag]
+--------+---------+------+--------+-----------+---------------+--------+------------+-----------+-----------+-------+-----------+--------+---------+---------+-----------+-----------+-----------+--------+-------+------+------------------+--------+----------------------+----------+-------+
| UserId | UnionId | Name | Avatar | StateCode | ManagerUserId | Mobile | HideMobile | Telephone | JobNumber | Title | WorkPlace | Remark | LoginId | DeptIds | DeptOrder | Extension | HiredDate | Active | Admin | Boss | ExclusiveAccount | Leader | ExclusiveAccountType | OrgEmail | Email |
+--------+---------+------+--------+-----------+---------------+--------+------------+-----------+-----------+-------+-----------+--------+---------+---------+-----------+-----------+-----------+--------+-------+------+------------------+--------+----------------------+----------+-------+

**Comment by eryajf** [comment]
您好 @shistory👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @shistory. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
先同步分组，再同步用户

**Comment by shistory** [comment]
#- "^61213417"  # 不需要同步的部门ID

- "^61213417" "^61213418" 
这块这么写正确吗

**Comment by shistory** [comment]
#- "^61213417" # 不需要同步的部门ID

- "^61213417" "^61213418"
这块这么写正确吗

**Comment by shistory** [comment]
#- "^61213417" # 不需要同步的部门ID
`- "^61213417" "^61213418"`

这块这么写正确吗

**Comment by eryajf** [comment]
不正确，注意遵循yaml的列表语法

**Comment by shistory** [comment]
dept-list: ^^61213417 ^61213418
这样么？
