### ISSUE TITLE
🚀 一些功能。。。 | [Feature]Some feature...

### ISSUE THREAD

**Issue by yangzhen376** [opsre/go-ldap-admin#375]
#### 您使用的场景？ | 1. Your usage scenarios?
我是做ippbx的需要帮客户创建LDAP通讯录，通过网页phpldapadmin添加删除用户感觉很麻烦不好操作，我看演示的网页里面没有IP电话号码添加的地方，有选项支持添加吗？

**Comment by eryajf** [comment]
您好 @yangzhen376👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @yangzhen376. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
有手机号的字段，没有IP的字段。看起来这是个比较小众的场景，这个项目目前只提供了通用的用户管理，你说的这个不支持。

**Comment by yangzhen376** [comment]
可能是我没有描述清楚，话机是IP类型的，办公电话号码，在LDAP属性里面是telephoneNumaner，现在用的确实也不是很多。

**Comment by eryajf** [comment]
恩恩，的确是场景比较窄，如果对go比较熟悉，可自行二开兼容
